import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { renderToStream } from "@react-pdf/renderer";
import { InvoiceTemplate } from "@/components/templates/InvoiceTemplate";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession(authOptions);

    if (!session || session.user?.role !== "admin") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id } = await params;

    const invoice = await prisma.invoice.findUnique({
      where: { id },
      include: {
        tenant: {
          select: {
            name: true,
            address: true,
            contactEmail: true,
            contactPhone: true,
            // taxId: true,
            logoUrl: true,
          },
        },
      },
    });

    if (!invoice) {
      return NextResponse.json({ error: "Invoice not found" }, { status: 404 });
    }

    const invoiceData = {
      number: invoice.invoiceNumber,
      date: invoice.createdAt.toLocaleDateString(),
      status: invoice.status,
      patientName: "Organization", // Using tenant name as organization
      patientIpp: invoice.tenantId.slice(0, 8),
      items: (invoice.lineItems as any[]).map((item: any) => ({
        description: item.description || "Service",
        quantity: item.quantity || 1,
        amount: item.amount || 0,
      })),
      subtotal: Number(invoice.amountHt),
      total: Number(invoice.amountHt) * (1 + Number(invoice.taxRate) / 100),
    };

    const facility = {
      name: invoice.tenant.name,
      address: invoice.tenant.address || "N/A",
      phone: invoice.tenant.contactPhone || "N/A",
      email: invoice.tenant.contactEmail || "N/A",
      logoUrl: invoice.tenant.logoUrl ?? undefined,
      // taxId: invoice.tenant.taxId ?? undefined,
    };

    const settings = {
      showLogo: true,
      includeQR: false,
      digitalSignature: false,
      watermark: false,
    };

    const labels = {
      invoice: "INVOICE",
      billed_to: "Organization",
      invoice_details: "Invoice Details",
      number: "Number",
      date: "Date",
      status: "Status",
      description: "Description",
      qty: "Qty",
      amount: "Amount",
      subtotal: "Subtotal",
      total: "Total",
      generated_by: "Generated by",
      confidential: "CONFIDENTIAL",
    };

    // Generate PDF stream
    const stream = await renderToStream(
      <InvoiceTemplate
        invoice={invoiceData}
        facility={facility}
        settings={settings}
        labels={labels}
      />
    );

    // Convert stream to buffer
    const chunks: Buffer[] = [];
    for await (const chunk of stream) {
      chunks.push(Buffer.from(chunk));
    }
    const buffer = Buffer.concat(chunks);

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${invoice.invoiceNumber}.pdf"`,
        "Cache-Control": "no-cache, no-store, must-revalidate",
      },
    });
  } catch (error) {
    console.error("[GET /api/admin/invoices/[id]/export]", error);
    return NextResponse.json(
      { error: "Failed to export invoice" },
      { status: 500 }
    );
  }
}
