import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { requireModulePermission } from "@/lib/permissions";
import prisma from "@/lib/prisma";

interface PharmacyPrescriptionItem {
  drug?: string;
  name?: string;
  quantity?: number | string;
  unit?: string;
}

export async function GET() {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const permCheck = requireModulePermission(session, "MODULE_PHARMACY", "read");
    if (!permCheck.ok) {
      return NextResponse.json({ error: permCheck.error }, { status: permCheck.status });
    }

    const prescriptions = await prisma.prescription.findMany({
      where: { tenantId: session.user.tenantId },
      orderBy: { prescribedAt: 'desc' },
      include: {
        patient: {
          select: {
            firstName: true,
            lastName: true,
            ipp: true
          }
        }
      }
    });

    // Fetch all doctors to map prescriberId to name
    const doctors = await prisma.tenantUser.findMany({
      where: { role: 'doctor' },
      select: { id: true, fullName: true }
    });

    const doctorMap = new Map(doctors.map(d => [d.id, d.fullName]));

    // Fetch all inventory for stock lookup
    const inventory = await prisma.medicationInventory.findMany({
      where: { isActive: true, tenantId: session.user.tenantId },
      select: { id: true, name: true, stock: true, unitPrice: true }
    });

    const inventoryMap = new Map(inventory.map(i => [i.name.toLowerCase(), i]));

    // Real invoice lines generated by the billing hook when a prescription was validated
    // (sourceId is `${prescriptionId}:${drugCode}`) — group by prescription id.
    const rxIds = prescriptions.map((rx) => rx.id);
    const invoiceLines = rxIds.length
      ? await prisma.patientInvoiceLine.findMany({
          where: {
            sourceType: "pharmacy_dispensation",
            OR: rxIds.map((rxId) => ({ sourceId: { startsWith: `${rxId}:` } })),
          },
          include: { invoice: true },
        })
      : [];

    const invoiceLinesByRx = new Map<string, typeof invoiceLines>();
    for (const line of invoiceLines) {
      const rxId = line.sourceId?.split(":")[0];
      if (!rxId) continue;
      const bucket = invoiceLinesByRx.get(rxId) ?? [];
      bucket.push(line);
      invoiceLinesByRx.set(rxId, bucket);
    }

    // We format the prescriptions to match the UI expectations
    const formattedData = prescriptions.map((rx) => {
      // items is a Json field, so we parse it safely
      let itemsList: PharmacyPrescriptionItem[] = [];
      try {
        if (typeof rx.items === 'string') {
          itemsList = JSON.parse(rx.items);
        } else if (Array.isArray(rx.items)) {
          itemsList = rx.items as unknown as PharmacyPrescriptionItem[];
        }
      } catch (e) {
        // ignore
      }

      // Enrich items with stock status and pricing
      const enrichedItems = itemsList.map((item) => {
        const drugName = item.drug || item.name || '';
        const invItem = inventoryMap.get(drugName.toLowerCase());
        let stockStatus: 'in_stock' | 'out_of_stock' | 'not_in_inventory' = 'not_in_inventory';
        let inventoryStock = 0;
        let unitPrice: number | null = null;
        let inventoryId: string | null = null;

        if (invItem) {
          inventoryId = invItem.id;
          inventoryStock = invItem.stock;
          unitPrice = invItem.unitPrice ? parseFloat(invItem.unitPrice.toString()) : null;
          stockStatus = invItem.stock > 0 ? 'in_stock' : 'out_of_stock';
        }

        return {
          ...item,
          stockStatus,
          inventoryStock,
          unitPrice,
          inventoryId
        };
      });

      // Calculate total cost
      const totalCost = enrichedItems.reduce((sum, item) => {
        const qty = parseFloat(String(item.quantity)) || 0;
        const price = item.unitPrice || 0;
        return sum + (qty * price);
      }, 0);

      const invoiceLines = invoiceLinesByRx.get(rx.id) ?? [];
      const invoice = invoiceLines[0]?.invoice ?? null;

      return {
        id: rx.id,
        patientName: `${rx.patient.firstName} ${rx.patient.lastName}`,
        prescriber: doctorMap.get(rx.prescriberId) || `ID: ${rx.prescriberId}`,
        date: rx.prescribedAt,
        status: rx.status === 'pending' ? 'Pending Queue' : rx.status === 'validated' ? 'Validated' : 'Dispensed',
        items: itemsList.length || 0,
        itemsData: enrichedItems,
        alert: false, // In a real app, this would come from rx.contraindicationCheck
        ipp: rx.patient.ipp,
        totalCost,
        invoiceId: invoice?.id ?? null,
        invoiceStatus: invoice?.status ?? null,
        invoiceTotal: invoice ? Number(invoice.subtotal) : null,
      };
    });

    return NextResponse.json({
      data: formattedData,
      total: formattedData.length,
      success: true,
    });
  } catch (error) {
    console.error("[GET /api/v1/pharmacy/prescriptions]", error);
    return NextResponse.json(
      { error: "Failed to fetch prescriptions", success: false },
      { status: 500 }
    );
  }
}
